"""Battery and Flanders capacity-tariff presets (indicative 2026 figures)."""

from __future__ import annotations

# Fluvius residential capacity tariff 2026, €/kW/year including 6% VAT.
# Source: Flemish regulator rates excl. VAT × 1.06 (YouPower / VNR 2026).
CAPACITY_TARIFFS_EUR_PER_KW_YEAR = {
    "Fluvius Antwerpen": 52.37,
    "Fluvius Halle-Vilvoorde": 59.41,
    "Fluvius Imewo": 57.45,
    "Fluvius Kempen": 59.58,
    "Fluvius Limburg": 51.99,
    "Fluvius Midden-Vlaanderen": 53.13,
    "Fluvius West": 60.53,
    "Fluvius Zenne-Dijle": 59.49,
    "Vlaams gemiddelde": 56.59,
}

MIN_BILLED_PEAK_KW = 2.5

# Round-trip is split equally over charge and discharge: η_c * η_d = RTE.
BATTERY_PRESETS = {
    "Aangepast": None,
    "Tesla Powerwall 3 (13.5 kWh)": {
        "capacity_kwh": 13.5,
        "charge_efficiency": 0.987,
        "discharge_efficiency": 0.987,
        "max_charge_kw": 11.5,
        "max_discharge_kw": 11.5,
        "min_soc_pct": 0.0,
        "cost_eur": 10500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Huawei LUNA2000-10-S0 (10 kWh)": {
        "capacity_kwh": 10.0,
        "charge_efficiency": 0.95,
        "discharge_efficiency": 0.95,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 0.0,
        "cost_eur": 6500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Huawei LUNA2000-15-S0 (15 kWh)": {
        "capacity_kwh": 15.0,
        "charge_efficiency": 0.95,
        "discharge_efficiency": 0.95,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 0.0,
        "cost_eur": 8500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Huawei LUNA2000-21-S1 (20.7 kWh)": {
        "capacity_kwh": 20.7,
        "charge_efficiency": 0.95,
        "discharge_efficiency": 0.95,
        "max_charge_kw": 10.5,
        "max_discharge_kw": 10.5,
        "min_soc_pct": 0.0,
        "cost_eur": 12000.0,
        "lifetime_years": 15.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "BYD Battery-Box HVS 10.2": {
        "capacity_kwh": 10.24,
        "charge_efficiency": 0.96,
        "discharge_efficiency": 0.96,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 5.0,
        "cost_eur": 6500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "BYD Battery-Box HVM 11.0": {
        "capacity_kwh": 11.04,
        "charge_efficiency": 0.96,
        "discharge_efficiency": 0.96,
        "max_charge_kw": 7.0,
        "max_discharge_kw": 7.0,
        "min_soc_pct": 5.0,
        "cost_eur": 7000.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Sigenergy SigenStor 10 kWh": {
        "capacity_kwh": 10.0,
        "charge_efficiency": 0.96,
        "discharge_efficiency": 0.96,
        "max_charge_kw": 10.0,
        "max_discharge_kw": 10.0,
        "min_soc_pct": 5.0,
        "cost_eur": 8000.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Enphase IQ Battery 5P": {
        "capacity_kwh": 5.0,
        "charge_efficiency": 0.948,
        "discharge_efficiency": 0.948,
        "max_charge_kw": 3.84,
        "max_discharge_kw": 3.84,
        "min_soc_pct": 0.0,
        "cost_eur": 5500.0,
        "lifetime_years": 15.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Marstek Venus E 3.0 (5.12 kWh)": {
        "capacity_kwh": 5.12,
        "charge_efficiency": 0.95,
        "discharge_efficiency": 0.95,
        "max_charge_kw": 2.5,
        "max_discharge_kw": 2.5,
        "min_soc_pct": 10.0,
        "cost_eur": 1199.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Marstek Venus E 3.0 (10.24 kWh, 2 units)": {
        "capacity_kwh": 10.24,
        "charge_efficiency": 0.95,
        "discharge_efficiency": 0.95,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 10.0,
        "cost_eur": 2349.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Marstek Venus E 3.0 (15.36 kWh, 3 units)": {
        "capacity_kwh": 15.36,
        "charge_efficiency": 0.95,
        "discharge_efficiency": 0.95,
        "max_charge_kw": 7.5,
        "max_discharge_kw": 7.5,
        "min_soc_pct": 10.0,
        "cost_eur": 3499.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Marstek Jupiter C+ (2.56 kWh)": {
        "capacity_kwh": 2.56,
        "charge_efficiency": 0.95,
        "discharge_efficiency": 0.95,
        "max_charge_kw": 0.8,
        "max_discharge_kw": 0.8,
        "min_soc_pct": 10.0,
        "cost_eur": 600.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Marstek Jupiter C+ (5.12 kWh)": {
        "capacity_kwh": 5.12,
        "charge_efficiency": 0.95,
        "discharge_efficiency": 0.95,
        "max_charge_kw": 0.8,
        "max_discharge_kw": 0.8,
        "min_soc_pct": 10.0,
        "cost_eur": 1099.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Marstek Jupiter C+ (10.24 kWh)": {
        "capacity_kwh": 10.24,
        "charge_efficiency": 0.95,
        "discharge_efficiency": 0.95,
        "max_charge_kw": 0.8,
        "max_discharge_kw": 0.8,
        "min_soc_pct": 10.0,
        "cost_eur": 2097.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Marstek Saturn B2500 (2.24 kWh)": {
        "capacity_kwh": 2.24,
        "charge_efficiency": 0.94,
        "discharge_efficiency": 0.94,
        "max_charge_kw": 0.8,
        "max_discharge_kw": 0.8,
        "min_soc_pct": 10.0,
        "cost_eur": 650.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Marstek Saturn B2500 (6.72 kWh, 3 modules)": {
        "capacity_kwh": 6.72,
        "charge_efficiency": 0.94,
        "discharge_efficiency": 0.94,
        "max_charge_kw": 0.8,
        "max_discharge_kw": 0.8,
        "min_soc_pct": 10.0,
        "cost_eur": 1650.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
}
