
[108 lines collapsed]

        "lifetime_years": 15.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "SolarEdge Home Battery 400V (9.7 kWh)": {
        "capacity_kwh": 9.7,
        "charge_efficiency": 0.972,
        "discharge_efficiency": 0.972,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 0.0,
        "cost_eur": 10500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "SolarEdge Home Battery 400V (19.4 kWh, 2×)": {
        "capacity_kwh": 19.4,
        "charge_efficiency": 0.972,
        "discharge_efficiency": 0.972,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 0.0,
        "cost_eur": 17500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "SolarEdge Home Battery 400V (29.1 kWh, 3×)": {
        "capacity_kwh": 29.1,
        "charge_efficiency": 0.972,
        "discharge_efficiency": 0.972,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 0.0,
        "cost_eur": 24500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "SolarEdge Home Battery 48V (9.2 kWh)": {
        "capacity_kwh": 9.2,
        "charge_efficiency": 0.972,
        "discharge_efficiency": 0.972,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 0.0,
        "cost_eur": 10000.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "SolarEdge Home Battery 48V (13.8 kWh, 3 modules)": {
        "capacity_kwh": 13.8,
        "charge_efficiency": 0.977,
        "discharge_efficiency": 0.977,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 0.0,
        "cost_eur": 12500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "SolarEdge Home Battery 48V (18.4 kWh, 4 modules)": {
        "capacity_kwh": 18.4,
        "charge_efficiency": 0.977,
        "discharge_efficiency": 0.977,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 0.0,
        "cost_eur": 15500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "SolarEdge Home Battery 48V (23 kWh, 5 modules)": {
        "capacity_kwh": 23.0,
        "charge_efficiency": 0.977,
        "discharge_efficiency": 0.977,
        "max_charge_kw": 5.0,
        "max_discharge_kw": 5.0,
        "min_soc_pct": 0.0,
        "cost_eur": 18500.0,
        "lifetime_years": 10.0,
        "self_discharge_pct_per_day": 0.0,
    },
    "Marstek Venus E 3.0 (5.12 kWh)": {
        "capacity_kwh": 5.12,
        "charge_efficiency": 0.95,

[86 lines collapsed]
